name: OpenShiftInstallBinary_OfflineFeatureBuilder
on:
  push:
    branches: 
      - offline
  pull_request:
    branches: 
      - offline
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Variable | Export Build Date
      run: |
        export varrundate="$(date +%y%m%d%I%M%S)"
        echo "::set-env name=varrundate::$varrundate"
    - name: Variable | Export Binary Last Commit Hash
      run: |
        git clone https://github.com/rhtconsulting/installer.git /tmp/installer
        cd /tmp/installer
        git checkout claudiol-offline-components
        export githash="$(git log -1 --pretty=%h)"
        echo "::set-env name=githash::$githash"
    - name: Docker.io Login
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin docker.io 
    - name: Quay.io Login
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin quay.io 
    - name: Builder Image | Compile Binary | openshift-install-offline
      run: |
        docker build . \
                 --file ./Dockerfile.builder \
                 --tag localhost/builder:offline
    - name: Carrier Image | Copy binary into cradle
      run: |
        docker build . \
                 --file ./Dockerfile \
                 --tag quay.io/${{ secrets.DOCKERHUB_ORGANIZATION  }}/openshift-install-mod:offline \
                 --tag docker.io/${{ secrets.DOCKERHUB_ORGANIZATION  }}/openshift-install-mod:offline \
                 --tag quay.io/${{ secrets.DOCKERHUB_ORGANIZATION  }}/openshift-install-mod:offline-${{ env.varrundate }}-${{ env.githash }} \
                 --tag docker.io/${{ secrets.DOCKERHUB_ORGANIZATION  }}/openshift-install-mod:offline-${{ env.varrundate }}-${{ env.githash }}
    - name: Image Push | openshift-install-offline | docker.io
      run: |
        docker push docker.io/${{ secrets.DOCKERHUB_ORGANIZATION  }}/openshift-install-mod:offline;        \
        docker push docker.io/${{ secrets.DOCKERHUB_ORGANIZATION  }}/openshift-install-mod:offline-${{ env.varrundate }}-${{ env.githash }}
    - name: Image Push | openshift-install-offline | quay.io
      run: |
        docker push quay.io/${{ secrets.DOCKERHUB_ORGANIZATION  }}/openshift-install-mod:offline;        \
        docker push quay.io/${{ secrets.DOCKERHUB_ORGANIZATION  }}/openshift-install-mod:offline-${{ env.varrundate }}-${{ env.githash }}
